In [26]:
import numpy as np

#there are 2**2N squares of size 2**-N x 2**-N
def mixing_scale(x_data, y_data, kappa):
    array_Size = x_data.shape[0];
    array_Size = array_Size/2;
    N = 1;
    while(True):
        mesh_size = 1/(2**N);
        x = 0;
        for i in range(2**N):
            y = 0;
            for k in range(2**N):
                function_Values = 0
                
                #this needs to change to fit data format
                x_matches = np.where(np.logical_and(x_data>=x, x_data<(x+mesh_size)));
                x_array = x_matches[0];
                #print(x, x+mesh_size);
                
                
                y_matches = np.where(np.logical_and(y_data>=y, y_data<(y+mesh_size)));
                y_array = y_matches[0];
                #print(y, y+mesh_size);
                
                matches = set(x_array) & set(y_array);
                numPoints = len(matches);
                #print(matches)
                
                if numPoints == 0:
                    #print("Empty cell");
                    break;
                
                for points in matches:
                    #print(points.shape);
                    if(points <= array_Size):
                        function_Values += 1;
                    else:
                        function_Values -= 1;
        
                if abs(function_Values/numPoints) > 1/kappa:
                    return 1/(2**(N-1));
                
                y += mesh_size;     
                
            x += mesh_size;
            
        N = N+1;
        #print(f"The iteration is {N}.");
        
    
    
    
    
        


In [76]:
grid = np.load("/Users/saraazimi/RTG/REU_Model_run_200x64x64.npy")
print(grid[0, 1, :, :])

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.01587302 0.01587302 0.01587302 ... 0.01587302 0.01587302 0.01587302]
 [0.03174603 0.03174603 0.03174603 ... 0.03174603 0.03174603 0.03174603]
 ...
 [0.96825397 0.96825397 0.96825397 ... 0.96825397 0.96825397 0.96825397]
 [0.98412698 0.98412698 0.98412698 ... 0.98412698 0.98412698 0.98412698]
 [1.         1.         1.         ... 1.         1.         1.        ]]


In [ ]:
mixing_scale(grid[199,0,:,:], grid[199, 1, :,:], 3)